# Reference: https://docs.github.com/en/actions/reference/workflows-and-actions/workflow-syntax

name: Android APK Build and Publish

run-name: Workflow triggered by ${{ github.actor }}

on:
  push:
    branches:
      - master

jobs:
  build-and-publish:
    name: build and publish apk on dropbox
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository to the github actions runner container
        uses: actions/checkout@v5
        with:
          submodules: recursive # Checkout submodules too | https://stackoverflow.com/questions/65077036/how-to-checkout-submodule-in-github-action
      - name: setup java 21
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'oracle'
      - name: Setup Android SDK # https://github.com/android-actions/setup-android
        uses: android-actions/setup-android@v3
      - name: Setup NDK # https://github.com/nttld/setup-ndk
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r28c # https://github.com/android/ndk/releases/tag/r28c ~ ndkVersion "28.2.13676358"
        env:
          ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}
      - name: Setup cmake # https://github.com/jwlawson/actions-setup-cmake
        uses: jwlawson/actions-setup-cmake@v2
        with:
          cmake-version: '4.1.2'
      - name: Build and package the apk
        shell: bash
        run: |
          ./gradlew assembleRelease
      - name: Publish the apk to Dropbox
        shell: bash
        run: |
          curl -X POST https://content.dropboxapi.com/2/files/upload \
            --header "Authorization: Bearer ${{ secrets.DROPBOX_ACCESS_TOKEN }}" \
            --header "Dropbox-API-Arg: {\"autorename\":false,\"mode\":\"overwrite\",\"mute\":false,\"path\":\"/ball-balancing-game.apk\",\"strict_conflict\":false}" \
            --header "Content-Type: application/octet-stream" \
            --data-binary @app/build/outputs/apk/release/app-release-unsigned.apk
